@startuml
'https://plantuml.com/class-diagram

class BattlesAppDesign1 {
    +main(String args[])
    +Start(Stage stage)
}

controllerClass o-- BattlesAppDesign1

class controllerClass{
    -TextField descBox
    -TextField dueDateBox
    -TextField nameBox
    -MenuItem save
    -Button submitButton

    saveFile(ActionEvent event)
    setNameDescDueDate(ActionEvent event)
}

class testClass{
    +testNameDueDateDesc()
    +testSaveFile()
}

@enduml